### ISSUE TITLE
Do you mean AES-256 (not SHA-256)?

### ISSUE THREAD

**Issue by jacobq** [aelesia/npx-cryptfile#2]
SHA-256 is a hash algorithm ("one-way" encryption; result cannot be converted back to the original), and it looks like you are passing the [`-aes-256-cbc` option](https://wiki.openssl.org/index.php/Enc) to OpenSSL
 [here](https://github.com/aelesia/npm-nodejs-shell/blob/master/src/shell/OpenSSL.ts#L10).
However, the README.md file states:

> Files are encrypted with OpenSSL SHA-256 algorithm.

**Comment by aelesia** [comment]
Yeah, it's AES. I updated the README a long time ago but I never pushed it. Thanks for the reminder!

**Comment by aelesia** [comment]
Fixed with https://github.com/aelesia/npx-cryptfile/commit/b823be7a40d69fecf950c4781bbee9243b28d115
